/**
 * Vendor the Iconify icons this repository actually references.
 *
 * Scans the repo for `prefix:name` icon references, fetches those icons from
 * the Iconify API, and writes one SVG sprite. The sprite is committed, so the
 * running site needs no CDN and no network.
 *
 * Run it after adding an icon name that is not already in the sprite:
 *
 *     deno task icons
 *
 * `deno task check` fails when the sprite is missing a name; that check is
 * offline and lives in `build-manifest.ts`.
 */

import { collectIconNames } from "./icon-scan.ts";
import { config } from "./_config.ts";
import { errorMessage, fail, info, muted, ok, warn } from "./style.ts";

const API = "https://api.iconify.design";

const output = new URL(config.iconSprite, `file://${config.root}`);

interface IconifyResponse {
  width?: number;
  height?: number;
  icons?: Record<string, { body: string; width?: number; height?: number }>;
  not_found?: string[];
}

async function fetchCollection(prefix: string, names: string[]): Promise<string[]> {
  const response = await fetch(`${API}/${prefix}.json?icons=${names.sort().join(",")}`);
  if (!response.ok) {
    throw new Error(`${prefix} returned ${response.status} ${response.statusText}`);
  }
  const data = await response.json() as IconifyResponse;
  for (const missing of data.not_found ?? []) {
    warn(`no such icon: ${prefix}:${missing}`);
  }

  const symbols: string[] = [];
  for (const [name, icon] of Object.entries(data.icons ?? {})) {
    const width = icon.width ?? data.width ?? 24;
    const height = icon.height ?? data.height ?? 24;
    symbols.push(
      `  <symbol id="${prefix}--${name}" viewBox="0 0 ${width} ${height}">${icon.body}</symbol>`,
    );
  }
  return symbols;
}

const byPrefix = await collectIconNames(config.root, config.iconSprite);
const total = [...byPrefix.values()].reduce((sum, names) => sum + names.size, 0);
if (total === 0) fail("no icon references found");

info(
  `found ${total} icon${total === 1 ? "" : "s"} across ${byPrefix.size} collection${
    byPrefix.size === 1 ? "" : "s"
  } ${muted([...byPrefix.keys()].sort().join(", "))}`,
);

const symbols: string[] = [];
for (const [prefix, names] of [...byPrefix.entries()].sort(([a], [b]) => a.localeCompare(b))) {
  try {
    symbols.push(...await fetchCollection(prefix, [...names]));
  } catch (error) {
    fail(`could not fetch ${prefix}: ${errorMessage(error)}`);
  }
}

const sprite = [
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">`,
  `  <!-- Generated by \`deno task icons\`. Edit the icon names in the repo, not this file. -->`,
  ...symbols,
  `</svg>`,
  "",
].join("\n");

await Deno.mkdir(new URL("./", output), { recursive: true });
await Deno.writeTextFile(output, sprite);
ok(`wrote ${symbols.length} symbols to ${config.iconSprite} ${muted(`(${sprite.length} bytes)`)}`);
